FROM --platform=linux/amd64 ubuntu:20.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential automake pkg-config autopoint libtool git bison flex

ADD . /repo
WORKDIR /repo
RUN ./synclibs.sh
RUN ./autogen.sh
RUN ./configure
RUN make -j8
RUN make install
ENV LD_LIBRARY_PATH=/usr/local/lib
RUN ldconfig
